name: Consolidar Artículos JSON

on:
  push:
    branches:
      - main
    paths:
      - 'articulos/*.json'

jobs:
  update-articles:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Ejecutar el script de consolidación
        run: node build-articles.js

      - name: Subir el archivo articles.json actualizado
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add articles.json
          git commit -m "Automatizado: Consolidar archivos JSON" || echo "No hay cambios para hacer commit"
          git push
